### ISSUE TITLE
Move bedrock clock procs from oregon-b to iowa-a

### ISSUE THREAD

**Issue by jgmize** [mozmeao/infra#1003]
- [x] [dev](https://github.com/mozmeao/www-config/pull/185)
- [x] [stage](https://github.com/mozmeao/www-config/pull/187)
- [x] [prod](https://github.com/mozmeao/www-config/pull/192)

**Comment by jgmize** [comment]
After merging https://github.com/mozmeao/www-config/pull/185 I saw the following error in the new clock proc deployment:

> ERROR: Failed to upload the new database: {u'git_sha': '14dc5801dec95f19ec795efa12f589d4802a413d', u'checksum': 'f464d5694117ed1ecbf71af346386a31539d2cbf28abd9f8c946370698ea212a', u'updated': 1547842671.21655, u'file_name': u'14dc5801de-f464d56941.db'}
[2019-01-18 20:17:51.884739] Clock job update_upload_database@bedrock-dev-clock-5bd4bb9c8-n56tn: CRASHED: Command 'python bin/run-db-upload.py' returned non-zero exit status 1

**Comment by jgmize** [comment]
Applied https://github.com/mozmeao/infra-private/commit/264aa76114d0efc315660a1c49495b8650bbd334 and restarted the clock pod. The clock job finished successfully, but I noticed a `Pocket API settings not found - skipping article refresh` in the logs, looking into that next.

**Comment by jgmize** [comment]
After merging https://github.com/mozmeao/www-config/pull/186 the `update_pocketfeed` command is succeeding in iowa-a.

**Comment by jgmize** [comment]
After merging https://github.com/mozmeao/www-config/pull/192 and [fixing a couple of secrets reference](https://github.com/mozmeao/www-config/commit/6d6c1aa9b36a4ed91ccd5b6b2b386f99f73d08c0) I got the following error in the logs:
```
ERROR: Failed to upload the new database: {u'git_sha': '54a48038904758e4f535877ad9d7d9fda9bf8067', u'checksum': '314b3ff0b710f14440935be554063af879048ca1acbbec76125f25b52e058c11', u'updated': 1548198683.288004, u'file_name': u'54a4803890-314b3ff0b7.db'}
[2019-01-22 23:11:24.061118] Clock job update_upload_database@bedrock-prod-clock-558ff5f4f7-l6bzz: CRASHED: Command 'python bin/run-db-upload.py' returned non-zero exit status 1
Traceback (most recent call last):
  File "bin/cron.py", line 159, in <module>
    main(sys.argv[1:])
  File "bin/cron.py", line 147, in main
    job.func()
  File "bin/cron.py", line 72, in run
    self.callback()
  File "/venv/lib/python2.7/site-packages/babis/babis.py", line 52, in wrapped
    fn(*args, **kwargs)
  File "bin/cron.py", line 112, in update_upload_database
    check_call('python bin/run-db-upload.py', shell=True)
  File "/usr/local/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'python bin/run-db-upload.py' returned non-zero exit status 1
```

The AWS secrets needed to upload the db looked right at first glance, but I'm double checking them now.

**Comment by jgmize** [comment]
Fixed AWS secrets, and the clock job finished successfully with the new secrets in iowa-a.
