### ISSUE TITLE
Manually test staging in Portland k8s

### ISSUE THREAD

**Issue by jwhitlock** [mozmeao/infra#527]
This checklist uses these URLs:

* Base: https://stage.mdn.moz.works
* CDN: https://stage-cdn.mdn.moz.works
* Demo: https://stage-files.mdn.moz.works
* Interactive Examples: https://interactive-examples.mdn.moz.works

# Manual Sanity Check

## Home page

Load https://stage.mdn.moz.works/en-US

* [x] Loads without errors
* [x] Does not have banner "MDN is currently in read-only maintenance mode. Learn more."
* [x] Has "Sign in" or "View Profile" at the top
* [x] Has entries for the Hacks Blog

## Article page

Load https://stage.mdn.moz.works/en-US/docs/Web/HTML

* [x] Loads without errors
* [x] No Maintenance Mode banner
* [x] Has "Sign in" or "View Profile" at the top

# Automated Checks

With a Kuma environment, [run the functional tests](https://kuma.readthedocs.io/en/latest/tests-ui.html), using a command like:

```
py.test -m "not login" tests/functional tests/redirects --base-url https://stage.mdn.moz.works --driver Chrome --driver-path /path/to/chromedriver
```

Some tests will fail the first time they are run against a server with cold caches. Some tests are flakey, and will intermittantly fail. If a test passes once in three tries, we consider it a success.

* [x] Functional tests pass

These check basic site functionality without logging in. It duplicates the Manual Sanity Check.

```
py.test -m "not login" tests/functional tests/redirects --base-url https://stage.mdn.moz.works --driver Chrome --driver-path /path/to/chromedriver
```

# Full Manual Tests

## Content tests

*Note: Many of these are candidates for headless testing*

These URLs should have similar results for anonymous or logged-in users:

* [x] https://stage-files.mdn.moz.works/en-US/docs/Learn/CSS/Styling_text/Fundamentals$samples/Color - 200, sample as a stand-alone page
* [x] https://stage-files.mdn.moz.works/files/12984/web-font-example.png - 200, PNG of some "Hipster ipsum" text
* [x] https://stage.mdn.moz.works/@api/deki/files/3613/=hut.jpg - 200, image of a hat
* [x] https://stage.mdn.moz.works/contribute.json - 200, project info
* [x] https://stage.mdn.moz.works/diagrams/workflow/workflow.svg - 200, SVG with images
* [x] https://stage.mdn.moz.works/en-US/dashboards/macros - 200, list of macros and page counts
* [x] https://stage.mdn.moz.works/en-US/dashboards/revisions - 200, list of recent changes
* [x] https://stage.mdn.moz.works/en-US/dashboards/spam - Redirects to signin page
* [x] https://stage.mdn.moz.works/en-US/docs/Learn/CSS/Styling_text/Fundamentals#Color - 200, with sample as iframe
* [x] https://stage.mdn.moz.works/en-US/docs/Learn/CSS/Styling_text/Fundamentals$toc - 200, HTML table of contents
* [x] https://stage.mdn.moz.works/en-US/docs/Web/HTML$children - 200, JSON list of child pages
* [x] https://stage.mdn.moz.works/en-US/docs/Web/HTML$compare?locale=en-US&to=1299417&from=1293895 - 200, compares revisions
* [x] https://stage.mdn.moz.works/en-US/docs/Web/HTML$history - 200, list of revisions
* [x] https://stage.mdn.moz.works/en-US/docs/Web/HTML$json - 200, JSON of page metadata
* [x] https://stage.mdn.moz.works/en-US/docs/Web/HTML$revision/1293895 - 200, historical revision
* [x] https://stage.mdn.moz.works/en-US/docs/Web/HTML$translate - Redirect to signin page
* [x] https://stage.mdn.moz.works/en-US/docs/all - 200, paginated list of docs
* [x] https://stage.mdn.moz.works/en-US/docs/ckeditor_config.js - 200, JavaScript
* [x] https://stage.mdn.moz.works/en-US/docs/feeds/atom/files/ - 200, Atom feed of changed files
* [x] https://stage.mdn.moz.works/en-US/docs/feeds/rss/all/ - 200, RSS feed of new pages
* [x] https://stage.mdn.moz.works/en-US/docs/feeds/rss/needs-review/ - 200, RSS feed of pages needing review
* [x] https://stage.mdn.moz.works/en-US/docs/feeds/rss/needs-review/technical - 200, RSS feed of pages needing technical review
* [x] https://stage.mdn.moz.works/en-US/docs/feeds/rss/revisions - 200, RSS feed of changes
* [x] https://stage.mdn.moz.works/en-US/docs/feeds/rss/tag/CSS - 200, RSS feed of pages with CSS tag
* [x] ~~https://stage.mdn.moz.works/en-US/docs/needs-review/editorial - 200, paginated list of documents~~ - Requires more than 120 second timeout
* [x] https://stage.mdn.moz.works/en-US/docs/tag/ARIA - 200, list of documents
* [x] https://stage.mdn.moz.works/en-US/docs/tags - 200, paginated list of tags
* [x] https://stage.mdn.moz.works/en-US/docs/top-level - 200, paginated list of documents
* [x] https://stage.mdn.moz.works/en-US/docs/with-errors - 200, (empty?) paginated list of documents
* [x] https://stage.mdn.moz.works/en-US/docs/without-parent - 200, paginated list of documents
* [x] https://stage.mdn.moz.works/en-US/miel  - 500 Internal Server Error
* [x] https://stage.mdn.moz.works/en-US/profiles/sheppy - 200, Sheppy's profile
* [x] https://stage.mdn.moz.works/en-US/promote/ - 200, Promote MDN with 4 buttons
* [x] https://stage.mdn.moz.works/en-US/search - 200, Search results
* [x] https://stage.mdn.moz.works/fellowship/ - 200, 2015 MDN Fellowship Program
* [x] https://stage.mdn.moz.works/files/12984/web-font-example.png - Redirects to https://stage-files.mdn.moz.works
* [x] https://stage.mdn.moz.works/fr/docs/feeds/rss/l10n-updates/ - 200, RSS feed of out-of-date pages
* [x] https://stage.mdn.moz.works/fr/docs/localization-tag/inprogress - 200, paginated list of documents
* [x] https://stage.mdn.moz.works/humans.txt - 200, list of GitHub usernames
* [x] https://stage.mdn.moz.works/media/kumascript-revision.txt - 200, git commit hash for kumascript
* [x] https://stage.mdn.moz.works/media/revision.txt - 200, git commit hash for kuma
* [x] https://stage.mdn.moz.works/presentations/microsummaries/index.html - 200, 2006 OSCON presentation
* [x] https://stage.mdn.moz.works/robots.txt - 200, robots disallow list
* [x] https://stage.mdn.moz.works/samples/webgl/sample3 - 200, Shows WebGL demo
* [x] https://stage.mdn.moz.works/sitemap.xml - 200, list of sitemaps
* [x] https://stage.mdn.moz.works/sitemaps/en-US/sitemap.xml - 200, list of en-US pages

## Anonymous tests

Test these URLs as an anonymous user:

* [x] https://stage.mdn.moz.works/admin/users/user/1/ - 302 redirect to the Admin login page, asking for a username and password.
* [x] https://stage.mdn.moz.works/en-US/docs/Web/HTML$edit - 302 redirect to user sign-in page, asking to Sign In with GitHub

## Regular Account Tests

Some things to try with a regular account, to exercise write functionality:

* [x] Create a new MDN user account (may require deleting your ``SocialAccount``)
* [x] Send a account recovery link for an existing MDN user account
* [x] Update the account profile
* [x] Add and verify a new email for a profile
* [x] Create a new page, such as https://stage.mdn.moz.works/en-US/docs/User:Test
* [x] Create a translation of the the page
* [x] Subscribe to a page, and change it with a different account
* [x] Update the original page with a KumaScript macro, such as ``{{cssxref("background")}}``.
* [x] Update the translation of a changed English page
* [x] Upload an image to the page
* [x] Add the image to the page content
* [x] Log out

## Admin Tests

* [x] Move a page
* [x] Delete a page
* [x] Restore a deleted page
* [x] View https://stage.mdn.moz.works/admin/users/user/1/

**Comment by escattone** [comment]
This is awesome, thanks @jwhitlock!

**Comment by jwhitlock** [comment]
And for "fun", as admin, https://developer.mozilla.org/admin/wiki/revision/ ([confidential bug  1372301](https://bugzilla.mozilla.org/show_bug.cgi?id=1372301))

**Comment by escattone** [comment]
First pass of functional tests:
```
(mdntest) rjohnson-25186:kuma rjohnson$ py.test -m "not login" tests/functional tests/redirects --base-url https://stage.mdn.moz.works --driver Chrome --driver-path ~/pytest-selenium/chromedriver
=============================================== test session starts ===============================================
platform darwin -- Python 2.7.12, pytest-3.0.7, py-1.4.33, pluggy-0.4.0
baseurl: https://stage.mdn.moz.works
driver: Chrome
sensitiveurl: .*
rootdir: /Users/rjohnson/repos/kuma, inifile: pytest.ini
plugins: base-url-1.1.0, html-1.10.1, rerunfailures-2.1.0, selenium-1.4.0, variables-1.4, xdist-1.16.0
collected 289 items

tests/functional/test_article.py ...s.....
tests/functional/test_article_edit.py .
tests/functional/test_article_revision.py ss
tests/functional/test_content_experiment.py ss
tests/functional/test_dashboard.py Fs.....
tests/functional/test_feedback.py F..
tests/functional/test_home.py .....Fs.
tests/functional/test_language_selector.py .
tests/functional/test_maintenance_mode_redirects.py sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
tests/functional/test_notfound.py .s.
tests/functional/test_profiles.py s
tests/functional/test_report.py F.
tests/functional/test_robots.py .
tests/functional/test_search.py ......s
tests/redirects/test_redirects.py ..........................................................................................................................................................................
============================================= short test summary info =============================================
SKIP [1] tests/functional/test_home.py:76: the server is not in maintenance mode
SKIP [1] tests/functional/test_search.py:119: the server is not in maintenance mode
SKIP [65] tests/functional/test_maintenance_mode_redirects.py:11: the server is not in maintenance mode
SKIP [1] tests/functional/test_profiles.py:7: the server is not in maintenance mode
SKIP [1] tests/functional/test_content_experiment.py:35: got empty parameter set ['exp_id', 'locale', 'slug'], function test_content_exp_redirect at /Users/rjohnson/repos/kuma/tests/functional/test_content_experiment.py:35
SKIP [1] tests/functional/test_dashboard.py:43: the server is not in maintenance mode
SKIP [1] tests/functional/test_article_revision.py:7: the server is not in maintenance mode
SKIP [1] tests/functional/test_notfound.py:20: the server is not in maintenance mode
SKIP [1] tests/functional/test_article_revision.py:28: the server is not in maintenance mode
SKIP [1] tests/functional/test_content_experiment.py:61: got empty parameter set ['exp_id', 'locale', 'slug', 'variant'], function test_content_exp_variant at /Users/rjohnson/repos/kuma/tests/functional/test_content_experiment.py:61
SKIP [1] tests/functional/test_article.py:45: the server is not in maintenance mode

==================================================== FAILURES =====================================================
_________________________________________________ test_dashboard __________________________________________________
Traceback (most recent call last):
  File "/Users/rjohnson/repos/kuma/tests/functional/test_dashboard.py", line 33, in test_dashboard
    assert page.dashboard_not_overflowing
AssertionError: assert False
 +  where False = <pages.dashboard.DashboardPage object at 0x108e24810>.dashboard_not_overflowing
------------------------------------------------- pytest-selenium -------------------------------------------------
URL: https://stage.mdn.moz.works/en-US/dashboards/revisions
__________________________________________________ test_location __________________________________________________
Traceback (most recent call last):
  File "/Users/rjohnson/repos/kuma/tests/functional/test_feedback.py", line 13, in test_location
    page = article_page.header.open_feedback()
  File "/Users/rjohnson/repos/kuma/tests/pages/base.py", line 153, in open_feedback
    return feedback_page.wait_for_page_to_load()
  File "/Users/rjohnson/repos/kuma/tests/pages/base.py", line 23, in wait_for_page_to_load
    self.wait.until(lambda s: el.get_attribute('data-ffo-opensans'))
  File "/Users/rjohnson/virtualenvs/mdntest/lib/python2.7/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
TimeoutException: Message:

------------------------------------------------- pytest-selenium -------------------------------------------------
URL: https://stage.mdn.moz.works/en-US/docs/MDN/Feedback
_______________________________________________ test_header_signin ________________________________________________
Traceback (most recent call last):
  File "/Users/rjohnson/repos/kuma/tests/functional/test_home.py", line 74, in test_header_signin
    assert 'https://github.com' in str(selenium.current_url)
AssertionError: assert 'https://github.com' in 'https://stage.mdn.moz.works/users/github/login/?next=%2Fen-US%2F'
 +  where 'https://stage.mdn.moz.works/users/github/login/?next=%2Fen-US%2F' = str('https://stage.mdn.moz.works/users/github/login/?next=%2Fen-US%2F')
 +    where 'https://stage.mdn.moz.works/users/github/login/?next=%2Fen-US%2F' = <selenium.webdriver.chrome.webdriver.WebDriver (session="79b681c26a944919e4799598635dcccd")>.current_url
------------------------------------------------- pytest-selenium -------------------------------------------------
URL: https://stage.mdn.moz.works/users/github/login/?next=%2Fen-US%2F
_______________________________________________ test_report_content _______________________________________________
Traceback (most recent call last):
  File "/Users/rjohnson/repos/kuma/tests/functional/test_report.py", line 23, in test_report_content
    assert page.header.is_report_content_url_expected(selenium, report_url)
AssertionError: assert False
 +  where False = <bound method Header.is_report_content_url_expected of <pages.base.Header object at 0x108edd410>>(<selenium.webdriver.chrome.webdriver.WebDriver (session="d9ccd042030b17e07c9eac92a0039199")>, 'https://stage.mdn.moz.works/en-US/docs/User:anonymous:uitest')
 +    where <bound method Header.is_report_content_url_expected of <pages.base.Header object at 0x108edd410>> = <pages.base.Header object at 0x108edd410>.is_report_content_url_expected
 +      where <pages.base.Header object at 0x108edd410> = <pages.article.ArticlePage object at 0x108edd710>.header
------------------------------------------------- pytest-selenium -------------------------------------------------
URL: about:blank
=============================================== 7 tests deselected ================================================
======================== 4 failed, 203 passed, 75 skipped, 7 deselected in 332.29 seconds =========================
```

Second pass:
```
(mdntest) rjohnson-25186:kuma rjohnson$ py.test -m "not login" tests/functional tests/redirects --base-url https://stage.mdn.moz.works --driver Chrome --driver-path ~/pytest-selenium/chromedriver
=============================================== test session starts ===============================================
platform darwin -- Python 2.7.12, pytest-3.0.7, py-1.4.33, pluggy-0.4.0
baseurl: https://stage.mdn.moz.works
driver: Chrome
sensitiveurl: .*
rootdir: /Users/rjohnson/repos/kuma, inifile: pytest.ini
plugins: base-url-1.1.0, html-1.10.1, rerunfailures-2.1.0, selenium-1.4.0, variables-1.4, xdist-1.16.0
collected 289 items

tests/functional/test_article.py ...s.....
tests/functional/test_article_edit.py .
tests/functional/test_article_revision.py ss
tests/functional/test_content_experiment.py ss
tests/functional/test_dashboard.py Fs.....
tests/functional/test_feedback.py ...
tests/functional/test_home.py ......s.
tests/functional/test_language_selector.py .
tests/functional/test_maintenance_mode_redirects.py sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
tests/functional/test_notfound.py .s.
tests/functional/test_profiles.py s
tests/functional/test_report.py F.
tests/functional/test_robots.py .
tests/functional/test_search.py ......s
tests/redirects/test_redirects.py ..........................................................................................................................................................................
============================================= short test summary info =============================================
SKIP [1] tests/functional/test_home.py:76: the server is not in maintenance mode
SKIP [1] tests/functional/test_search.py:119: the server is not in maintenance mode
SKIP [65] tests/functional/test_maintenance_mode_redirects.py:11: the server is not in maintenance mode
SKIP [1] tests/functional/test_profiles.py:7: the server is not in maintenance mode
SKIP [1] tests/functional/test_content_experiment.py:35: got empty parameter set ['exp_id', 'locale', 'slug'], function test_content_exp_redirect at /Users/rjohnson/repos/kuma/tests/functional/test_content_experiment.py:35
SKIP [1] tests/functional/test_dashboard.py:43: the server is not in maintenance mode
SKIP [1] tests/functional/test_article_revision.py:7: the server is not in maintenance mode
SKIP [1] tests/functional/test_notfound.py:20: the server is not in maintenance mode
SKIP [1] tests/functional/test_article_revision.py:28: the server is not in maintenance mode
SKIP [1] tests/functional/test_content_experiment.py:61: got empty parameter set ['exp_id', 'locale', 'slug', 'variant'], function test_content_exp_variant at /Users/rjohnson/repos/kuma/tests/functional/test_content_experiment.py:61
SKIP [1] tests/functional/test_article.py:45: the server is not in maintenance mode

==================================================== FAILURES =====================================================
_________________________________________________ test_dashboard __________________________________________________
Traceback (most recent call last):
  File "/Users/rjohnson/repos/kuma/tests/functional/test_dashboard.py", line 33, in test_dashboard
    assert page.dashboard_not_overflowing
AssertionError: assert False
 +  where False = <pages.dashboard.DashboardPage object at 0x10c309810>.dashboard_not_overflowing
------------------------------------------------- pytest-selenium -------------------------------------------------
URL: https://stage.mdn.moz.works/en-US/dashboards/revisions
_______________________________________________ test_report_content _______________________________________________
Traceback (most recent call last):
  File "/Users/rjohnson/repos/kuma/tests/functional/test_report.py", line 23, in test_report_content
    assert page.header.is_report_content_url_expected(selenium, report_url)
AssertionError: assert False
 +  where False = <bound method Header.is_report_content_url_expected of <pages.base.Header object at 0x10cc78d10>>(<selenium.webdriver.chrome.webdriver.WebDriver (session="ebb73175e8f4f10ea4c20fa2a2aced4a")>, 'https://stage.mdn.moz.works/en-US/docs/User:anonymous:uitest')
 +    where <bound method Header.is_report_content_url_expected of <pages.base.Header object at 0x10cc78d10>> = <pages.base.Header object at 0x10cc78d10>.is_report_content_url_expected
 +      where <pages.base.Header object at 0x10cc78d10> = <pages.article.ArticlePage object at 0x10cc7d290>.header
------------------------------------------------- pytest-selenium -------------------------------------------------
URL: about:blank
=============================================== 7 tests deselected ================================================
======================== 2 failed, 205 passed, 75 skipped, 7 deselected in 197.65 seconds =========================
```

Third pass:
```
(mdntest) rjohnson-25186:kuma rjohnson$ py.test -m "not login" tests/functional tests/redirects --base-url https://stage.mdn.moz.works --driver Chrome --driver-path ~/pytest-selenium/chromedriver
=============================================== test session starts ===============================================
platform darwin -- Python 2.7.12, pytest-3.0.7, py-1.4.33, pluggy-0.4.0
baseurl: https://stage.mdn.moz.works
driver: Chrome
sensitiveurl: .*
rootdir: /Users/rjohnson/repos/kuma, inifile: pytest.ini
plugins: base-url-1.1.0, html-1.10.1, rerunfailures-2.1.0, selenium-1.4.0, variables-1.4, xdist-1.16.0
collected 289 items

tests/functional/test_article.py ...s.....
tests/functional/test_article_edit.py .
tests/functional/test_article_revision.py ss
tests/functional/test_content_experiment.py ss
tests/functional/test_dashboard.py Fs.....
tests/functional/test_feedback.py ...
tests/functional/test_home.py ......s.
tests/functional/test_language_selector.py .
tests/functional/test_maintenance_mode_redirects.py sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
tests/functional/test_notfound.py .s.
tests/functional/test_profiles.py s
tests/functional/test_report.py ..
tests/functional/test_robots.py .
tests/functional/test_search.py ......s
tests/redirects/test_redirects.py ..........................................................................................................................................................................
============================================= short test summary info =============================================
SKIP [1] tests/functional/test_home.py:76: the server is not in maintenance mode
SKIP [1] tests/functional/test_search.py:119: the server is not in maintenance mode
SKIP [65] tests/functional/test_maintenance_mode_redirects.py:11: the server is not in maintenance mode
SKIP [1] tests/functional/test_profiles.py:7: the server is not in maintenance mode
SKIP [1] tests/functional/test_content_experiment.py:35: got empty parameter set ['exp_id', 'locale', 'slug'], function test_content_exp_redirect at /Users/rjohnson/repos/kuma/tests/functional/test_content_experiment.py:35
SKIP [1] tests/functional/test_dashboard.py:43: the server is not in maintenance mode
SKIP [1] tests/functional/test_article_revision.py:7: the server is not in maintenance mode
SKIP [1] tests/functional/test_notfound.py:20: the server is not in maintenance mode
SKIP [1] tests/functional/test_article_revision.py:28: the server is not in maintenance mode
SKIP [1] tests/functional/test_content_experiment.py:61: got empty parameter set ['exp_id', 'locale', 'slug', 'variant'], function test_content_exp_variant at /Users/rjohnson/repos/kuma/tests/functional/test_content_experiment.py:61
SKIP [1] tests/functional/test_article.py:45: the server is not in maintenance mode

==================================================== FAILURES =====================================================
_________________________________________________ test_dashboard __________________________________________________
Traceback (most recent call last):
  File "/Users/rjohnson/repos/kuma/tests/functional/test_dashboard.py", line 33, in test_dashboard
    assert page.dashboard_not_overflowing
AssertionError: assert False
 +  where False = <pages.dashboard.DashboardPage object at 0x10b482810>.dashboard_not_overflowing
------------------------------------------------- pytest-selenium -------------------------------------------------
URL: https://stage.mdn.moz.works/en-US/dashboards/revisions
=============================================== 7 tests deselected ================================================
======================== 1 failed, 206 passed, 75 skipped, 7 deselected in 195.41 seconds =========================
```

**Comment by escattone** [comment]
The https://stage.mdn.moz.works/en-US/docs/needs-review/editorial endpoint consistently times out for me.

**Comment by escattone** [comment]
It looks like the `test_dashboard` test within `tests/functional/test_dashboard.py` is consistently failing. I need to look into that further.

**Comment by jwhitlock** [comment]
I ran the tests a few times. I wanted to see if I could duplicate, and then I was curious and dug in.

* With https://github.com/mozilla/kuma/pull/4441 (improve external link tests) - 1 failure, ``test_dashboard``
* With master - All passed
* With master, just ``test_dashboard.py`` tests, and dropping into ``--pdb`` - ``test_dashboard`` failed.

Here's what's going on:

<img width="1185" alt="screenshot 2017-10-04 09 16 54" src="https://user-images.githubusercontent.com/286017/31180682-da0456d6-a8e4-11e7-9bb2-40a2a103ea58.png">

The test is that the content (the most recent page diff, 1430 px) is not wider than the client window (1201 px). As you can see from the screenshot, the content is a diff for an edit I made.

This dashboard test was not part of the original intern tests  ([dashboards.js](https://github.com/mozilla/kuma/blob/1e0a69b569587e1fe741efcd717c46d79e9e655a/tests/ui/tests/dashboards.js)), and was added with the [re-write to Python](https://github.com/mozilla/kuma/commit/864a874c9c5f82de20bb91419bc687041283b519).

@stephaniehobson - I know December 2016 was a long time ago, but do you remember why this test was added? My CSS / JavaScript isn't good enough to see why the element should not overflow.

**Comment by stephaniehobson** [comment]
This was a regression or never fixed properly. Since the admin pages are not a priority this is unlikely to be fixed. I filed Bug 1405690 and suggest you remove the test.

**Comment by escattone** [comment]
Thanks for looking into this @jwhitlock and @stephaniehobson !

**Comment by escattone** [comment]
I pulled the latest Kuma code (which has the latest improvements to the functional tests -- thanks @jwhitlock and @stephaniehobson!) and re-ran the functional tests. Nice and clean on the first pass! Going to check-off the functional tests.
```
(mdntest) rjohnson-25186:kuma rjohnson$ py.test -m "not login" tests/functional tests/redirects --base-url https://stage.mdn.moz.works --driver Chrome --driver-path ~/pytest-selenium/chromedriver
=============================================== test session starts ===============================================
platform darwin -- Python 2.7.12, pytest-3.0.7, py-1.4.33, pluggy-0.4.0
baseurl: https://stage.mdn.moz.works
driver: Chrome
sensitiveurl: .*
rootdir: /Users/rjohnson/repos/kuma, inifile: pytest.ini
plugins: base-url-1.1.0, html-1.10.1, rerunfailures-2.1.0, selenium-1.4.0, variables-1.4, xdist-1.16.0
collected 290 items

tests/functional/test_article.py ...s.....
tests/functional/test_article_edit.py .
tests/functional/test_article_revision.py ss
tests/functional/test_content_experiment.py ss
tests/functional/test_dashboard.py .xs.....
tests/functional/test_feedback.py ...
tests/functional/test_home.py ......s.
tests/functional/test_language_selector.py .
tests/functional/test_maintenance_mode_redirects.py sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
tests/functional/test_notfound.py .s.
tests/functional/test_profiles.py s
tests/functional/test_report.py ..
tests/functional/test_robots.py .
tests/functional/test_search.py ......s
tests/redirects/test_redirects.py ..........................................................................................................................................................................
============================================= short test summary info =============================================
SKIP [65] tests/functional/test_maintenance_mode_redirects.py:11: the server is not in maintenance mode
SKIP [1] tests/functional/test_home.py:78: the server is not in maintenance mode
SKIP [1] tests/functional/test_profiles.py:7: the server is not in maintenance mode
SKIP [1] tests/functional/test_content_experiment.py:35: got empty parameter set ['exp_id', 'locale', 'slug'], function test_content_exp_redirect at /Users/rjohnson/repos/kuma/tests/functional/test_content_experiment.py:35
SKIP [1] tests/functional/test_search.py:119: the server is not in maintenance mode
SKIP [1] tests/functional/test_article_revision.py:7: the server is not in maintenance mode
SKIP [1] tests/functional/test_dashboard.py:55: the server is not in maintenance mode
SKIP [1] tests/functional/test_notfound.py:20: the server is not in maintenance mode
SKIP [1] tests/functional/test_article_revision.py:28: the server is not in maintenance mode
SKIP [1] tests/functional/test_content_experiment.py:61: got empty parameter set ['exp_id', 'locale', 'slug', 'variant'], function test_content_exp_variant at /Users/rjohnson/repos/kuma/tests/functional/test_content_experiment.py:61
SKIP [1] tests/functional/test_article.py:45: the server is not in maintenance mode
XFAIL tests/functional/test_dashboard.py::test_dashboard_overflow
  bug 1405690: fails for some revision diffs

=============================================== 7 tests deselected ================================================
======================== 207 passed, 75 skipped, 7 deselected, 1 xfailed in 216.06 seconds ========================

```

**Comment by escattone** [comment]
I also deployed the latest Kuma image (`777b114`) to `stage.mdn.moz.works`.

**Comment by escattone** [comment]
Now that https://github.com/mozilla/kuma/pull/4454 is submitted, I can continue this testing first thing tomorrow morning.

**Comment by jwhitlock** [comment]
Working on the checklist as well. We've only tested the read-only features, so I hope the remaining issues we find are minor 😬

**Comment by jwhitlock** [comment]
The remaining issue is that https://stage.mdn.moz.works/en-US/docs/needs-review/editorial doesn't load. It does load in the production deployment, so it probably because stage has a less powerful database.

There is no traceback in paper trail. Instead, after about 2 minutes, there's a restart of the web service:

```
[1] [CRITICAL] WORKER TIMEOUT (pid:60)
[75] [INFO] Booting worker with pid: 75
```

The endpoint would probably work by increasing the ``KUMA_GUNICORN_TIMEOUT`` from ``120`` seconds to a larger number.  However, we're planning on re-writing this view to do the work in a background task, so I think it is OK it doesn't work at the moment in the staging environment.

**Comment by jwhitlock** [comment]
AWS Staging looks good!

**Comment by escattone** [comment]
FWIW, I did try increasing the `KUMA_GUNICORN_TIMEOUT` from `120` to `240` two days ago, but it didn't seem to work.
